import '../../components/range-slider/index';
import '../../components/dropdown/index';
import '../../components/guests-dropdown/index';
import '../../components/room-dropdown/index';
import '../../components/checkbox-list/index';
import '../../components/field/index';
import '../../components/like-button/index';
import '../../components/review/index';
import './form-elements.scss';
